package org.repetitor.database.scenarios;

import org.repetitor.database.dao.RegionDao;
import org.repetitor.database.model.Region;
import org.repetitor.database.model.enums.RegionType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ScenarioRegion extends DataBaseScenario {
    @Autowired
    private RegionDao regionDao;

    @Override
    @Transactional
    protected void execute() {
        Region russia = createRegion("Россия", RegionType.COUNTRY);
        Region moscow = createRegion("Москва", "Москве", RegionType.CITY, russia);
        createRegion("Авиамоторная", RegionType.SUBWAY, moscow);
        createRegion("Автозаводская", RegionType.SUBWAY, moscow);
        createRegion("Академическая", RegionType.SUBWAY, moscow);
        createRegion("Александровский сад", RegionType.SUBWAY, moscow);
        createRegion("Алексеевская", RegionType.SUBWAY, moscow);
        createRegion("Алма-Атинская", RegionType.SUBWAY, moscow);
        createRegion("Алтуфьево", RegionType.SUBWAY, moscow);
        createRegion("Аннино", RegionType.SUBWAY, moscow);
        createRegion("Арбатская (Арбатско-Покровская линия)", RegionType.SUBWAY, moscow);
        createRegion("Арбатская (Филевская линия)", RegionType.SUBWAY, moscow);
        createRegion("Аэропорт", RegionType.SUBWAY, moscow);
        createRegion("Бабушкинская", RegionType.SUBWAY, moscow);
        createRegion("Багратионовская", RegionType.SUBWAY, moscow);
        createRegion("Баррикадная", RegionType.SUBWAY, moscow);
        createRegion("Бауманская", RegionType.SUBWAY, moscow);
        createRegion("Беговая", RegionType.SUBWAY, moscow);
        createRegion("Белорусская", RegionType.SUBWAY, moscow);
        createRegion("Беляево", RegionType.SUBWAY, moscow);
        createRegion("Бибирево", RegionType.SUBWAY, moscow);
        createRegion("Библиотека имени Ленина", RegionType.SUBWAY, moscow);
        createRegion("Борисово", RegionType.SUBWAY, moscow);
        createRegion("Боровицкая", RegionType.SUBWAY, moscow);
        createRegion("Ботанический сад", RegionType.SUBWAY, moscow);
        createRegion("Братиславская", RegionType.SUBWAY, moscow);
        createRegion("Бульвар адмирала Ушакова", RegionType.SUBWAY, moscow);
        createRegion("Бульвар Дмитрия Донского", RegionType.SUBWAY, moscow);
        createRegion("Бульвар Рокоссовского", RegionType.SUBWAY, moscow);
        createRegion("Бунинская аллея", RegionType.SUBWAY, moscow);
        createRegion("Варшавская", RegionType.SUBWAY, moscow);
        createRegion("ВДНХ", RegionType.SUBWAY, moscow);
        createRegion("Владыкино", RegionType.SUBWAY, moscow);
        createRegion("Водный стадион", RegionType.SUBWAY, moscow);
        createRegion("Войковская", RegionType.SUBWAY, moscow);
        createRegion("Волгоградский проспект", RegionType.SUBWAY, moscow);
        createRegion("Волжская", RegionType.SUBWAY, moscow);
        createRegion("Волоколамская", RegionType.SUBWAY, moscow);
        createRegion("Воробьевы горы", RegionType.SUBWAY, moscow);
        createRegion("Выставочная", RegionType.SUBWAY, moscow);
        createRegion("Выхино", RegionType.SUBWAY, moscow);
        createRegion("Деловой центр", RegionType.SUBWAY, moscow);
        createRegion("Динамо", RegionType.SUBWAY, moscow);
        createRegion("Дмитровская", RegionType.SUBWAY, moscow);
        createRegion("Добрынинская", RegionType.SUBWAY, moscow);
        createRegion("Домодедовская", RegionType.SUBWAY, moscow);
        createRegion("Достоевская", RegionType.SUBWAY, moscow);
        createRegion("Дубровка", RegionType.SUBWAY, moscow);
        createRegion("Жулебино", RegionType.SUBWAY, moscow);
        createRegion("Зябликово", RegionType.SUBWAY, moscow);
        createRegion("Измайловская", RegionType.SUBWAY, moscow);
        createRegion("Калужская", RegionType.SUBWAY, moscow);
        createRegion("Кантемировская", RegionType.SUBWAY, moscow);
        createRegion("Каховская", RegionType.SUBWAY, moscow);
        createRegion("Каширская", RegionType.SUBWAY, moscow);
        createRegion("Киевская", RegionType.SUBWAY, moscow);
        createRegion("Китай-город", RegionType.SUBWAY, moscow);
        createRegion("Кожуховская", RegionType.SUBWAY, moscow);
        createRegion("Коломенская", RegionType.SUBWAY, moscow);
        createRegion("Комсомольская", RegionType.SUBWAY, moscow);
        createRegion("Коньково", RegionType.SUBWAY, moscow);
        createRegion("Красногвардейская", RegionType.SUBWAY, moscow);
        createRegion("Краснопресненская", RegionType.SUBWAY, moscow);
        createRegion("Красносельская", RegionType.SUBWAY, moscow);
        createRegion("Красные ворота", RegionType.SUBWAY, moscow);
        createRegion("Крестьянская застава", RegionType.SUBWAY, moscow);
        createRegion("Кропоткинская", RegionType.SUBWAY, moscow);
        createRegion("Крылатское", RegionType.SUBWAY, moscow);
        createRegion("Кузнецкий мост", RegionType.SUBWAY, moscow);
        createRegion("Кузьминки", RegionType.SUBWAY, moscow);
        createRegion("Кунцевская", RegionType.SUBWAY, moscow);
        createRegion("Курская", RegionType.SUBWAY, moscow);
        createRegion("Кутузовская", RegionType.SUBWAY, moscow);
        createRegion("Ленинский проспект", RegionType.SUBWAY, moscow);
        createRegion("Лермонтовский проспект", RegionType.SUBWAY, moscow);
        createRegion("Лубянка", RegionType.SUBWAY, moscow);
        createRegion("Люблино", RegionType.SUBWAY, moscow);
        createRegion("Марксистская", RegionType.SUBWAY, moscow);
        createRegion("Марьина роща", RegionType.SUBWAY, moscow);
        createRegion("Марьино", RegionType.SUBWAY, moscow);
        createRegion("Маяковская", RegionType.SUBWAY, moscow);
        createRegion("Медведково", RegionType.SUBWAY, moscow);
        createRegion("Международная", RegionType.SUBWAY, moscow);
        createRegion("Менделеевская", RegionType.SUBWAY, moscow);
        createRegion("Митино", RegionType.SUBWAY, moscow);
        createRegion("Молодежная", RegionType.SUBWAY, moscow);
        createRegion("Монорельса Выставочный центр", RegionType.SUBWAY, moscow);
        createRegion("Монорельса Телецентр", RegionType.SUBWAY, moscow);
        createRegion("Монорельса Улица Академика Королева", RegionType.SUBWAY, moscow);
        createRegion("Монорельса Улица Милашенкова", RegionType.SUBWAY, moscow);
        createRegion("Монорельса Улица Сергея Эйзенштейна", RegionType.SUBWAY, moscow);
        createRegion("Монорельсовой дороги Тимирязевская", RegionType.SUBWAY, moscow);
        createRegion("Мякинино", RegionType.SUBWAY, moscow);
        createRegion("Нагатинская", RegionType.SUBWAY, moscow);
        createRegion("Нагорная", RegionType.SUBWAY, moscow);
        createRegion("Нахимовский проспект", RegionType.SUBWAY, moscow);
        createRegion("Новогиреево", RegionType.SUBWAY, moscow);
        createRegion("Новокосино", RegionType.SUBWAY, moscow);
        createRegion("Новокузнецкая", RegionType.SUBWAY, moscow);
        createRegion("Новослободская", RegionType.SUBWAY, moscow);
        createRegion("Новоясеневская", RegionType.SUBWAY, moscow);
        createRegion("Новые Черемушки", RegionType.SUBWAY, moscow);
        createRegion("Октябрьская", RegionType.SUBWAY, moscow);
        createRegion("Октябрьское поле", RegionType.SUBWAY, moscow);
        createRegion("Орехово", RegionType.SUBWAY, moscow);
        createRegion("Отрадное", RegionType.SUBWAY, moscow);
        createRegion("Охотныйряд", RegionType.SUBWAY, moscow);
        createRegion("Павелецкая", RegionType.SUBWAY, moscow);
        createRegion("Парк культуры", RegionType.SUBWAY, moscow);
        createRegion("Парк Победы", RegionType.SUBWAY, moscow);
        createRegion("Партизанская", RegionType.SUBWAY, moscow);
        createRegion("Первомайская", RegionType.SUBWAY, moscow);
        createRegion("Перово", RegionType.SUBWAY, moscow);
        createRegion("Петровско-Разумовская", RegionType.SUBWAY, moscow);
        createRegion("Печатники", RegionType.SUBWAY, moscow);
        createRegion("Пионерская", RegionType.SUBWAY, moscow);
        createRegion("Планерная", RegionType.SUBWAY, moscow);
        createRegion("Площадь Ильича", RegionType.SUBWAY, moscow);
        createRegion("Площадь Революции", RegionType.SUBWAY, moscow);
        createRegion("Полежаевская", RegionType.SUBWAY, moscow);
        createRegion("Полянка", RegionType.SUBWAY, moscow);
        createRegion("Пражская", RegionType.SUBWAY, moscow);
        createRegion("Преображенская площадь", RegionType.SUBWAY, moscow);
        createRegion("Пролетарская", RegionType.SUBWAY, moscow);
        createRegion("Проспект Вернадского", RegionType.SUBWAY, moscow);
        createRegion("Проспект Мира", RegionType.SUBWAY, moscow);
        createRegion("Профсоюзная", RegionType.SUBWAY, moscow);
        createRegion("Пушкинская", RegionType.SUBWAY, moscow);
        createRegion("Пятницкое шоссе", RegionType.SUBWAY, moscow);
        createRegion("Речной вокзал", RegionType.SUBWAY, moscow);
        createRegion("Рижская", RegionType.SUBWAY, moscow);
        createRegion("Римская", RegionType.SUBWAY, moscow);
        createRegion("Рязанский проспект", RegionType.SUBWAY, moscow);
        createRegion("Савеловская", RegionType.SUBWAY, moscow);
        createRegion("Свиблово", RegionType.SUBWAY, moscow);
        createRegion("Севастопольская", RegionType.SUBWAY, moscow);
        createRegion("Семеновская", RegionType.SUBWAY, moscow);
        createRegion("Серпуховская", RegionType.SUBWAY, moscow);
        createRegion("Славянский бульвар", RegionType.SUBWAY, moscow);
        createRegion("Смоленская (Арбатско-Покровская линия)", RegionType.SUBWAY, moscow);
        createRegion("Смоленская (Филевская линия)", RegionType.SUBWAY, moscow);
        createRegion("Сокол", RegionType.SUBWAY, moscow);
        createRegion("Сокольники", RegionType.SUBWAY, moscow);
        createRegion("Спартак", RegionType.SUBWAY, moscow);
        createRegion("Спортивная", RegionType.SUBWAY, moscow);
        createRegion("Сретенский бульвар", RegionType.SUBWAY, moscow);
        createRegion("Строгино", RegionType.SUBWAY, moscow);
        createRegion("Студенческая", RegionType.SUBWAY, moscow);
        createRegion("Сухаревская", RegionType.SUBWAY, moscow);
        createRegion("Сходненская", RegionType.SUBWAY, moscow);
        createRegion("Таганская", RegionType.SUBWAY, moscow);
        createRegion("Тверская", RegionType.SUBWAY, moscow);
        createRegion("Театральная", RegionType.SUBWAY, moscow);
        createRegion("Текстильщики", RegionType.SUBWAY, moscow);
        createRegion("Теплый стан", RegionType.SUBWAY, moscow);
        createRegion("Тимирязевская", RegionType.SUBWAY, moscow);
        createRegion("Третьяковская", RegionType.SUBWAY, moscow);
        createRegion("Тропарево", RegionType.SUBWAY, moscow);
        createRegion("Трубная", RegionType.SUBWAY, moscow);
        createRegion("Тульская", RegionType.SUBWAY, moscow);
        createRegion("Тургеневская", RegionType.SUBWAY, moscow);
        createRegion("Тушинская", RegionType.SUBWAY, moscow);
        createRegion("Улица Академика Янгеля", RegionType.SUBWAY, moscow);
        createRegion("Улица Горчакова", RegionType.SUBWAY, moscow);
        createRegion("Улица Скобелевская", RegionType.SUBWAY, moscow);
        createRegion("Улица Старокачаловская", RegionType.SUBWAY, moscow);
        createRegion("Улица 1905 года", RegionType.SUBWAY, moscow);
        createRegion("Университет", RegionType.SUBWAY, moscow);
        createRegion("Филевский парк", RegionType.SUBWAY, moscow);
        createRegion("Фили", RegionType.SUBWAY, moscow);
        createRegion("Фрунзенская", RegionType.SUBWAY, moscow);
        createRegion("Царицыно", RegionType.SUBWAY, moscow);
        createRegion("Цветной бульвар", RegionType.SUBWAY, moscow);
        createRegion("Черкизовская", RegionType.SUBWAY, moscow);
        createRegion("Чертановская", RegionType.SUBWAY, moscow);
        createRegion("Чеховская", RegionType.SUBWAY, moscow);
        createRegion("Чистые пруды", RegionType.SUBWAY, moscow);
        createRegion("Чкаловская", RegionType.SUBWAY, moscow);
        createRegion("Шаболовская", RegionType.SUBWAY, moscow);
        createRegion("Шипиловская", RegionType.SUBWAY, moscow);
        createRegion("Шоссе Энтузиастов", RegionType.SUBWAY, moscow);
        createRegion("Щелковская", RegionType.SUBWAY, moscow);
        createRegion("Щукинская", RegionType.SUBWAY, moscow);
        createRegion("Электрозаводская", RegionType.SUBWAY, moscow);
        createRegion("Юго-Западная", RegionType.SUBWAY, moscow);
        createRegion("Южная", RegionType.SUBWAY, moscow);
        createRegion("Ясенево ", RegionType.SUBWAY, moscow);

        Region piter = createRegion("Санкт-Петербург", "Санкт-Петербурге", RegionType.CITY, russia);
        createRegion("Автово", RegionType.SUBWAY, piter);
        createRegion("Адмиралтейская", RegionType.SUBWAY, piter);
        createRegion("Академическая", RegionType.SUBWAY, piter);
        createRegion("Балтийская", RegionType.SUBWAY, piter);
        createRegion("Бухарестская", RegionType.SUBWAY, piter);
        createRegion("Василеостровская", RegionType.SUBWAY, piter);
        createRegion("Владимирская", RegionType.SUBWAY, piter);
        createRegion("Волковская", RegionType.SUBWAY, piter);
        createRegion("Выборгская", RegionType.SUBWAY, piter);
        createRegion("Горьковская", RegionType.SUBWAY, piter);
        createRegion("Гостиный двор", RegionType.SUBWAY, piter);
        createRegion("Гражданский проспект", RegionType.SUBWAY, piter);
        createRegion("Девяткино", RegionType.SUBWAY, piter);
        createRegion("Достоевская", RegionType.SUBWAY, piter);
        createRegion("Елизаровская", RegionType.SUBWAY, piter);
        createRegion("Звёздная", RegionType.SUBWAY, piter);
        createRegion("Звенигородская", RegionType.SUBWAY, piter);
        createRegion("Кировский завод", RegionType.SUBWAY, piter);
        createRegion("Комендантский проспект", RegionType.SUBWAY, piter);
        createRegion("Крестовский остров", RegionType.SUBWAY, piter);
        createRegion("Купчино", RegionType.SUBWAY, piter);
        createRegion("Ладожская", RegionType.SUBWAY, piter);
        createRegion("Ленинский проспект", RegionType.SUBWAY, piter);
        createRegion("Лесная", RegionType.SUBWAY, piter);
        createRegion("Лиговский проспект", RegionType.SUBWAY, piter);
        createRegion("Ломоносовская", RegionType.SUBWAY, piter);
        createRegion("Маяковская", RegionType.SUBWAY, piter);
        createRegion("Международная", RegionType.SUBWAY, piter);
        createRegion("Московская", RegionType.SUBWAY, piter);
        createRegion("Московские ворота", RegionType.SUBWAY, piter);
        createRegion("Нарвская", RegionType.SUBWAY, piter);
        createRegion("Невский проспект", RegionType.SUBWAY, piter);
        createRegion("Новочеркасская", RegionType.SUBWAY, piter);
        createRegion("Обводный канал", RegionType.SUBWAY, piter);
        createRegion("Обухово", RegionType.SUBWAY, piter);
        createRegion("Озерки", RegionType.SUBWAY, piter);
        createRegion("Парк Победы", RegionType.SUBWAY, piter);
        createRegion("Парнас", RegionType.SUBWAY, piter);
        createRegion("Петроградская", RegionType.SUBWAY, piter);
        createRegion("Пионерская", RegionType.SUBWAY, piter);
        createRegion("Площадь Александра Невского 1", RegionType.SUBWAY, piter);
        createRegion("Площадь Александра Невского 2", RegionType.SUBWAY, piter);
        createRegion("Площадь Восстания", RegionType.SUBWAY, piter);
        createRegion("Площадь Ленина", RegionType.SUBWAY, piter);
        createRegion("Площадь Мужества", RegionType.SUBWAY, piter);
        createRegion("Политехническая", RegionType.SUBWAY, piter);
        createRegion("Приморская", RegionType.SUBWAY, piter);
        createRegion("Пролетарская", RegionType.SUBWAY, piter);
        createRegion("Проспект Большевиков", RegionType.SUBWAY, piter);
        createRegion("Проспект Ветеранов", RegionType.SUBWAY, piter);
        createRegion("Проспект Просвещения", RegionType.SUBWAY, piter);
        createRegion("Пушкинская", RegionType.SUBWAY, piter);
        createRegion("Рыбацкое", RegionType.SUBWAY, piter);
        createRegion("Садовая", RegionType.SUBWAY, piter);
        createRegion("Сенная площадь", RegionType.SUBWAY, piter);
        createRegion("Спасская", RegionType.SUBWAY, piter);
        createRegion("Спортивная", RegionType.SUBWAY, piter);
        createRegion("Старая Деревня", RegionType.SUBWAY, piter);
        createRegion("Технологический институт 1", RegionType.SUBWAY, piter);
        createRegion("Технологический институт 2", RegionType.SUBWAY, piter);
        createRegion("Удельная", RegionType.SUBWAY, piter);
        createRegion("Улица Дыбенко", RegionType.SUBWAY, piter);
        createRegion("Фрунзенская", RegionType.SUBWAY, piter);
        createRegion("Чёрная речка", RegionType.SUBWAY, piter);
        createRegion("Чернышевская", RegionType.SUBWAY, piter);
        createRegion("Чкаловская", RegionType.SUBWAY, piter);
        createRegion("Электросила", RegionType.SUBWAY, piter);

    }

    private Region createRegion(String name, RegionType type) {
        Region c = new Region();
        c.setName(name);
        c.setType(type);
        regionDao.save(c);
        return c;
    }

    private Region createRegion(String name, String name2, RegionType type, Region parent) {
        Region c = new Region();
        c.setName(name);
        c.setName2(name2);
        c.setType(type);
        c.setParent(parent);
        regionDao.save(c);
        return c;
    }

    private Region createRegion(String name, RegionType type, Region parent) {
        Region c = new Region();
        c.setName(name);
        c.setName2(name);
        c.setType(type);
        c.setParent(parent);
        regionDao.save(c);
        return c;
    }
}
